# docker-compose.yml - Otobüs Bilet Satış Platformu

version: '3.8'

services:
  web:
    build: .
    container_name: bus-ticket-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./database:/var/www/html/database
      - ./uploads:/var/www/html/uploads
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
    restart: unless-stopped
    networks:
      - bus-ticket-network

networks:
  bus-ticket-network:
    driver: bridge

volumes:
  database:
  uploads:

